autopoint: add sanity check for configure.ac
a curious user might try to run the script from a random directory expecting
to see help output. in such a case it's better to fail early with an error
message instead of first creating directories and files the user would have
to cleanup manually afterwards.

diff --git a/src/autopoint.in b/src/autopoint.in
--- a/src/autopoint.in
+++ b/src/autopoint.in
@@ -1,6 +1,11 @@
 #!/bin/sh
 m4src=@datadir@/m4
 
+if ! test -e configure.ac ; then
+	echo "$0: error: configure.ac not found" >&2
+	exit 1
+fi
+
 mkdir -p m4 intl po
 for i in $m4src/*.m4 ; do
 	cp -f $i m4/
